#!/bin/sh
lock() {
    i3lock -i ~/Bilder/appa_1920_1080.png -e -f -t
    # xss-lock --transfer-sleep-lock -- i3lock --nofork -i ~/Bilder/appa_1920_1080.png -e -f -t
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
